task: StrategyQA
train_ratio: 0.9

seed: 42

# MODEL
generator_model: gpt-4o-mini
critic_model: microsoft/deberta-v3-base
add_special_tokens: True

# PARAMETER-EFFICIENT FINETUNING
use_lora: True
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: all-linear
lora_modules_to_save:
lora_bias: none

# MODE
critic_mode: classification
score_mode:

# SEARCH PARAMS
beam_size: 2
num_candidates: 4
max_length: 8
early_stopping: True
only_eval_answers: False

# QUERY_PARAMS
temperature: 0.7
frequency_penalty: 0
presence_penalty: 0
stop: ["\n", "\n\n", "\n\n\n"]
max_tokens: 64

# TRAINING_PARAMS
offline_warmup_path:
num_epochs_offline_warmup:

use_blackbox_warmup: True
num_epochs_blackbox_warmup: 1
num_candidates_blackbox_warmup: 4

num_online_finetuning_repeat: 1

num_epochs: 1
batch_size: 32
gradient_accumulation_steps: 1

l2_reg_coef: 1.
energy_temp: 5.
warmup_steps: 10
learning_rate: 1.E-4
min_lr: 1.E-4
T_lr: 1000

use_outcome_supervision: True
num_negatives_for_training: 1
qa_template: "Q: <Q>\n\nA: <A>"

# EVALUATION
eval_blackbox: True
eval_unfinetuned: False
num_eval_rounds: 1

log_with_wandb: False

# LOW-COST COLAB SUBSETS
max_train_samples: 64
max_eval_samples: 64
